# Generated by Django 5.0.6 on 2024-06-08 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.CreateModel(
            name='WaterUsage',
            fields=[
                ('barcode', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=255)),
                ('water_used', models.FloatField()),
                ('amount_paid', models.FloatField()),
                ('billing_month', models.IntegerField()),
                ('billing_year', models.IntegerField()),
                ('is_recent', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.user')),
            ],
        ),
    ]
