# Generated by Django 5.0.6 on 2024-06-09 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_award_tempwinner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='category',
            field=models.CharField(choices=[('incentive', 'Teşvik Ödülü'), ('general', 'Genel Ödül')], max_length=50),
        ),
        migrations.AlterField(
            model_name='award',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='award',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='TempWinner',
        ),
    ]
