# Generated by Django 5.0.6 on 2024-06-09 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_alter_award_category_alter_award_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='category',
            field=models.CharField(choices=[('incentive', 'Incentive'), ('general', 'General')], max_length=10),
        ),
        migrations.AlterField(
            model_name='award',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myApp.user'),
        ),
    ]
